📦 ci: add a safeguard so it doesn't move tags like it did just now

diff --git a/.github/workflows/tag_and_deploy.yml b/.github/workflows/tag_and_deploy.yml
--- a/.github/workflows/tag_and_deploy.yml
+++ b/.github/workflows/tag_and_deploy.yml
@@ -33,6 +33,18 @@ jobs:
               sudo apt install jq
           fi
 
+          # Get the latest Git tag
+          latest_tag=$(git describe --tags --abbrev=0)
+
+          echo "Current version: $curr_version"
+          echo "Latest Git tag: $latest_tag"
+
+          # If the current version matches the last tag, fail the build
+          if [ "$curr_version" == "$latest_tag" ]; then
+            echo "Error: The version in package.json matches the latest tag. Please increment the version to deploy."
+            exit 1
+          fi
+
           curr_version=$(jq ".version" package.json)
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"
